### ISSUE TITLE
Doesn't work with SDK 2013 Singleplayer

### ISSUE THREAD

**Issue by pudingus** [Gocnak/sdk-2013-hammer#46] opened 2018-09-20 07:01 UTC
When I launch it from Singleplayer bin directory I get this error: 
![image](https://user-images.githubusercontent.com/39903631/45801105-232b2c80-bcb3-11e8-937c-e39555207ed8.png)

> The procedure entry point HushAsserts could not be located in the dynamic link library D:\games\steamapps\common\Source SDK Base 2013 Singleplayer\bin\hammer\bin\hammer_dll.dll

When I launch it from Multiplayer bin, it works fine.

**Comment by Gocnak** [comment] 2018-09-20 17:31
Are you on the `upcoming` branch for SP? The binaries for SP are outdated due to MP being a faster iteration/less stable or something. I'm not sure how to fix it, as HushAsserts seems to be part of the Valve standard library.

**Comment by pudingus** [comment] 2018-09-20 20:30
Yeah I am, also tried the current branch - same problem. 
I just found out that if I copy "tier0.dll" from MP, it works. But then there is another problem, when I open certain maps hammer crashes (even when launching from MP bin)

**Comment by Gocnak** [comment] 2018-09-20 20:38
Hm, could be tied to #45 . We'll see when we merge in SCell's branch if it gets fixed. I'll close this issue for now, since the original problem was solved, and the new one is a duplicate of #45.

**Closed by Gocnak** 2018-09-20 20:38 UTC
